In [1]:
# 例子：如果array=[1, 1, 3, 1, 4, 2]，如果k=1，则返回3，有(3,4),(1,2),(2,3)这3对；如果k=2，则返回2，有(1,3),(2,4)这两对
def find_pairs(array, k):
    if len(array)<2 or k < 0:
        return 0
    array.sort()
    lower = 0
    higher = 1
    v_lower = -1
    v_higher = -1
    res = 0
    while lower < len(array) and higher < len(array):
        tmp_res = array[higher] - array[lower]
        if lower < higher and tmp_res >= k:
            if (tmp_res == k and (array[lower] != v_lower or array[higher] != v_higher)):
                res += 1
                v_lower = array[lower]
                v_higher = array[higher]
            lower += 1
        else:
            higher += 1
    return res

array=[1, 1, 3, 1, 4, 2]
k=2
find_pairs(array, k)

2

In [ ]:
# 本题希望你用机器学习算法在提供的训练数据上训练一个模型，并在测试数据上汇报预测的效果，请看最下面的问题说明。
import numpy
import sklearn.metrics
x_train = numpy.array([[-0.8 , -0.8 ],
       [-0.8 , -0.48],
       [-0.8 , -0.16],
       [-0.8 ,  0.16],
       [-0.8 ,  0.48],
       [-0.8 ,  0.8 ],
       [-0.48, -0.8 ],
       [-0.48, -0.48],
       [-0.48, -0.16],
       [-0.48,  0.16],
       [-0.48,  0.48],
       [-0.48,  0.8 ],
       [-0.16, -0.8 ],
       [-0.16, -0.48],
       [-0.16, -0.16],
       [-0.16,  0.16],
       [-0.16,  0.48],
       [-0.16,  0.8 ],
       [ 0.16, -0.8 ],
       [ 0.16, -0.48],
       [ 0.16, -0.16],
       [ 0.16,  0.16],
       [ 0.16,  0.48],
       [ 0.16,  0.8 ],
       [ 0.48, -0.8 ],
       [ 0.48, -0.48],
       [ 0.48, -0.16],
       [ 0.48,  0.16],
       [ 0.48,  0.48],
       [ 0.48,  0.8 ],
       [ 0.8 , -0.8 ],
       [ 0.8 , -0.48],
       [ 0.8 , -0.16],
       [ 0.8 ,  0.16],
       [ 0.8 ,  0.48],
       [ 0.8 ,  0.8 ]])
y_train = numpy.array([19.16695052, 13.22042364, 10.06006317, 10.07024508, 13.09231182, 19.28932958, 13.09699286,  7.02510918,  3.77707591,  3.75280753, 6.98970389, 12.95676487, 10.01139805,  3.83283814,  0.75967419, 0.66507218,  4.08057273,  9.83142631, 10.14434347,  3.87253675, 0.48726579,  0.85708327,  3.62700781,  9.98383945, 13.03754723, 6.91194217,  3.80872056,  3.75064037,  6.96504836, 13.03395797, 19.18596309, 13.22441868,  9.97017209,  9.9608034 , 13.03983236, 19.25797367])
x_test = numpy.array([[ 0.60066134,  0.75514525],
       [ 0.62493958,  0.74354012],
       [ 0.68757087,  0.68514481],
       [ 0.70646998,  0.74249948],
       [-0.86394857,  0.22874845],
       [ 0.2215083 ,  0.49629939],
       [ 0.44835169,  0.98975117],
       [-0.76399039, -0.94554732],
       [ 0.39836963, -0.10177351],
       [ 0.91524278,  0.53612187],
       [-0.41065771,  0.56951352],
       [ 0.16812817,  0.7284085 ],
       [ 0.8898741 ,  0.73323525],
       [-0.86431684,  0.12372524],
       [-0.2547392 ,  0.56557855],
       [ 0.45626855, -0.98097258],
       [ 0.01415029,  0.26820149],
       [-0.97811162, -0.2954746 ],
       [ 0.78104109, -0.22334335],
       [-0.60341742,  0.60002444],
       [-0.79763483,  0.29683079],
       [-0.64229142,  0.66181316],
       [ 0.84009633, -0.1485917 ],
       [ 0.46944093,  0.27329434],
       [ 0.41647943, -0.22300934]])
y_test = numpy.array([14.0648327 , 14.1768829 , 14.2222626 , 15.71538637, 11.79833645, 4.46068088, 17.72559463, 21.99815467,  2.53139972, 16.72969738, 7.42901727,  8.35165552, 20.00799747, 11.42873041,  5.70221722, 17.6655741 ,  0.91620557, 15.67473377,  9.98291571, 10.84098305, 10.81040218, 12.7695035 , 10.84929453,  4.34147587,  3.45347178])

def eval_model(true_label, prediction):
    return numpy.sqrt(sklearn.metrics.mean_squared_error(true_label, prediction))

# 问题定义：上面提供了训练数据(x_train, y_train)，请在训练数据上训练模型，在x_test上用模型预测，并和真实值y_test对比计算模型效果。这里提供了评估模型效果的函数eval_model（可以看出模型效果指标为RMSE）。由于面试工具提供的python分析工具有限，本题鼓励候选人在自己电脑环境上对数据进行分析，构造模型使它的测试集RMSE在0.1左右，并用numpy, pandas, sklearn中的函数将算法实现在下面。（切换屏幕时面试工具会提醒作弊，这个不用理会，本题不对切屏做限制）
# 这里提供一个简单例子，可以看到RMSE > 6，效果是很差的
import sklearn.linear_model
model = sklearn.linear_model.LinearRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)
print(f"RMSE: {eval_model(y_test, pred)}")

import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn import preprocessing

forest = RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=8,
           max_features='log2', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
           oob_score=False, random_state=1, verbose=0, warm_start=False)
forest.fit(x_train, y_train)
pred = forest.predict(x_test)
print("RMSE: ", eval_model(y_test, pred))

In [95]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn import preprocessing
from sklearn.grid_search import GridSearchCV

forest = RandomForestRegressor(criterion='mse',
                                n_estimators=10, 
                                random_state=1,
                                n_jobs=2)
forest.fit(x_train, y_train)
pred = forest.predict(x_test)
print("RMSE: ", eval_model(y_test, pred))


params = {"criterion": ['mse', 'mae'],
          "n_estimators": [100,120,300,500],
          "max_depth": [5,8,15,25,None],
          "max_features": ["log2","sqrt","auto"],
          "min_samples_split": [1,2,5,10,15,100]
         }
params = {"criterion": ['mse', 'mae'] "n_estimators": [100,120,300,500], "max_depth": [5,8,15,25,None], "max_features": ["log2","sqrt","auto"], "min_samples_split":[1,2,5,10,15,100] }
grid = GridSearchCV(estimator=forest, param_grid=params)
grid.fit(x_train, y_train)
print grid.best_estimator_
print "grid.best_score_", grid.best_score_

('RMSE: ', 2.8240818794142704)
RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=8,
           max_features='log2', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=2,
           oob_score=False, random_state=1, verbose=0, warm_start=False)
grid.best_score_ -0.611246815698


In [29]:
X_train, X_test, y_train, y_test = train_test_split(x_train, y_train, random_state=100, test_size=0.2)

scaler = preprocessing.StandardScaler().fit(X_train)
print scaler.mean_
print scaler.scale_
print X_train[:3,:]
X_train = scaler.transform(X_train)
print X_train[:3,:]
# 对测试集做一样的变换
X_test = scaler.transform(X_test)
print X_test[:3,:]

(28, 2)
(8, 2)
[-0.05714286  0.03428571]
[ 0.5205962   0.52259947]
[[-0.8   0.8 ]
 [-0.8  -0.48]
 [ 0.16 -0.8 ]]
[[-1.42693538  1.46520296]
 [-1.42693538 -0.98409154]
 [ 0.41710419 -1.59641516]]
[[-1.42693538 -1.59641516]
 [ 0.41710419 -0.98409154]
 [ 1.6464639  -0.37176791]]


### 模型训练

In [55]:
from sklearn import neighbors, datasets, preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = datasets.load_iris()
# dir(iris)
# iris.feature_names
# iris.target_names

# train_X = iris.data
# train_y = iris.target
# print "train_X.shape:{} ".format(train_X.shape)
# print "train_y.shape:{} ".format(train_y.shape)
train_X, train_y = iris.data[:, :2], iris.target
# X_train, X_test, y_train, y_test = train_test_split(train_X, train_y, random_state=33, test_size=0.2)
# print X_train.shape
# print X_test.shape
X_train, X_test, y_train, y_test = train_test_split(train_X, train_y, random_state=100, test_size=0.2)
print "X_train.shape", X_train.shape
print "X_test.shape", X_test.shape
print "X_train[:3,:]\n", X_train[:3,:] #幅度范围不一样，为了保证训练的顺畅，做一些数据预处理
scaler = preprocessing.StandardScaler().fit(X_train) #拿到一组变换的参数
print "scaler.mean_", scaler.mean_
print "scaler.scale_", scaler.scale_
X_train = scaler.transform(X_train) #对原始数据做变换（缩放、平移）
print "X_train[:3,:]\n", X_train[:3,:]
X_test = scaler.transform(X_test) # 对测试集做一样的变换
print "X_test[:3,:]\n", X_test[:3,:]

knn = neighbors.KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
print "knn model:\n", knn

y_pred = knn.predict(X_test)
print "y_pred", y_pred
print "y_test.shape", y_test.shape
print "y_test==y_pred:\n", y_test==y_pred
print "accuracy_score", sum(y_test==y_pred)/float(y_test.shape[0])
print "accuracy_score", accuracy_score(y_test, y_pred)

X_train.shape (120, 2)
X_test.shape (30, 2)
X_train[:3,:]
[[ 5.5  2.4]
 [ 5.7  2.8]
 [ 6.   2.2]]
scaler.mean_ [ 5.78916667  3.04583333]
scaler.scale_ [ 0.79987456  0.43106377]
X_train[:3,:]
[[-0.36151502 -1.49823154]
 [-0.11147581 -0.57029459]
 [ 0.263583   -1.96220002]]
X_test[:3,:]
[[ 0.76366141 -0.57029459]
 [-1.23665225  0.82161084]
 [ 2.38891626 -1.03426306]]
knn model:
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
y_pred [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 1 2 0 2 0 1 1 1 0 1 2]
y_test.shape (30,)
y_test==y_pred:
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False  True False  True  True  True  True
  True False  True  True  True  True]
accuracy_score 0.9
accuracy_score 0.9


In [56]:
from sklearn import svm
svc = svm.SVC(kernel='rbf')
svc.fit(X_train, y_train)
print "svc model:\n", svc
svm_pred = svc.predict(X_test)
print "accuracy_score", accuracy_score(svm_pred, y_test)

svc model:
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
accuracy_score 0.833333333333


In [60]:
import numpy as np
from sklearn.grid_search import GridSearchCV
params = {"n_neighbors": np.arange(1,6),"metric": ["euclidean", "cityblock"]}
grid = GridSearchCV(estimator=knn, param_grid=params)
grid.fit(X_train, y_train)
# print "grid.best_estimator_:\n", grid.best_estimator_
# print "grid.best_score_", grid.best_score_

GridSearchCV(cv=None, error_score='raise',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_neighbors': array([1, 2, 3, 4, 5]), 'metric': ['euclidean', 'cityblock']},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=0)

### 洗数据

In [49]:
import sys
import os
import numpy as np
import pandas as pd
from datetime import datetime

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', -1)

# file_results = sys.argv[1]
file_results = "check_data_aggr.out.20200707"
file_path = os.path.join("./", file_results)
table_name = ""
dt = ""
logs = ""
df_table_dict = {}
df_covered_dict = {}
df_reco_avg_dict = {}
df_reco_med_dict = {}
df_visited_dict = {}
df_covered_online_dict = {}
df_user_split_dict = {}
df_user_case_dict = {}
dt_cur = ""
flag = 0

with open(file_path) as f:
    for idx, line in enumerate(f.readlines()):
        elements = line.strip().split('\t')
        if flag == 0 and len(elements) == 3:
            table_name = elements[0]
            dt = elements[1]
            logs = elements[2]
            if table_name not in df_table_dict:
                df_table_dict[table_name] = {}
            df_table_dict[table_name][dt] = logs
        elif len(elements) == 12:
            flag = 1
            prefix = elements[0]
            dt = elements[1]
            # transfer
            dt_str = dt[0:4] + "-" + dt[4:6] + "-" + dt[6:8]
            dayofweek = datetime.strptime(dt_str, '%Y-%m-%d').weekday()
#             print(dt_str, dayofweek)
            covered_cnt = elements[2]
            reco_cnt_avg = elements[4]
            reco_cnt_50 = elements[7]
            pf_covered = prefix + "_c"
            pf_avg = prefix + "_a"
            pf_50 = prefix + "_m"
            if pf_covered not in df_table_dict:
                df_table_dict[pf_covered] = {}
                df_covered_dict[pf_covered] = {}
            if pf_avg not in df_table_dict:
                df_table_dict[pf_avg] = {}
                df_reco_avg_dict[pf_avg] = {}
            if pf_50 not in df_table_dict:
                df_table_dict[pf_50] = {}
                df_reco_med_dict[pf_50] = {}
                
            df_table_dict[pf_covered][dt] = covered_cnt
            df_table_dict[pf_avg][dt] = reco_cnt_avg
            df_table_dict[pf_50][dt] = reco_cnt_50
            
            df_covered_dict[pf_covered][dt] = covered_cnt
            df_reco_avg_dict[pf_avg][dt] = reco_cnt_avg
            df_reco_med_dict[pf_50][dt] = reco_cnt_50
        elif len(elements) == 8:
            dt_cur = elements[0]
            df_visited_dict["reg"] = {}
            df_visited_dict["noreg"] = {}
            user_reg_show = elements[3]
            user_noreg_show = elements[4]
            user_reg_click = elements[6]
            user_noreg_click = elements[7]
            df_visited_dict["reg"]["show"] = user_reg_show
            df_visited_dict["noreg"]["show"] = user_noreg_show
            df_visited_dict["reg"]["click"] = user_reg_click
            df_visited_dict["noreg"]["click"] = user_noreg_click
        elif flag == 1 and len(elements) == 3:
            if elements[0] == "yes":
                df_visited_dict["reg"]["covered"] = elements[2]
            elif elements[0] == "no":
                df_visited_dict["noreg"]["covered"] = elements[2]
        elif (flag == 1 or flag == 2) and len(elements) == 2:
            flag = 2
            prefix = elements[0]
            covered_cnt_online = elements[1]
            df_covered_online_dict[prefix] = covered_cnt_online
        elif (flag == 2 or flag == 3) and len(elements) == 3:
            flag = 3
            name = elements[0]
            if name not in df_user_split_dict:
                df_user_split_dict[name] = {}
            key = elements[1]
            value = elements[2]
            df_user_split_dict[name][key] = value
        elif flag == 3 and len(elements) == 2:
            if len(df_user_case_dict) == 0:
                df_user_case_dict["tailNumber"] = {}
                df_user_case_dict["bdp_uuid"] = {}
            key = elements[0]
            value = elements[1]
            df_user_case_dict["tailNumber"][idx] = key
            df_user_case_dict["bdp_uuid"][idx] = value
            
            
df_table = pd.DataFrame(df_table_dict)
df_covered = pd.DataFrame(df_covered_dict)
df_reco_avg = pd.DataFrame(df_reco_avg_dict)
df_reco_med = pd.DataFrame(df_reco_med_dict)
df_visited_online = pd.DataFrame(df_visited_dict)
df_covered_online = pd.Series(df_covered_online_dict)
df_user_case = pd.DataFrame(df_user_case_dict)

print(df_table)
# print(df_covered)
# print(df_reco_avg)
# print(df_reco_med)
print("\n--- df_visited_online ---")
print(df_visited_online)

print("\n--- df_covered_online ---")
print(df_covered_online)

for name in df_user_split_dict:
    print("\n--- df_user_split_" + name + " ---")
    print(pd.Series(df_user_split_dict[name]))

print("\n--- df_user_case ---")
print(df_user_case.reset_index(drop=True))
                

         3:hot_fudao_a 3:hot_fudao_c 3:hot_fudao_m 4:ar_online_a  \
20200701  33.93649507   528148        30.0          3.89240729     
20200702  34.32712776   526140        30.0          4.33741754     
20200703  35.82087553   530765        30.0          4.13258269     
20200704  38.70173743   456420        30.0          3.76812628     
20200705  38.3482445    422815        30.0          3.48728534     
20200706  35.47087111   554398        30.0          3.70227385     
20200707  34.87823772   522165        30.0          4.4122378      

         4:ar_online_c 4:ar_online_m 5:hot_kw_a 5:hot_kw_c 5:hot_kw_m  \
20200701  181964        2.0           2.2823     36547      1.0         
20200702  149927        3.0           2.8857     23816      1.0         
20200703  166168        3.0           2.8881     23812      1.0         
20200704  196262        2.0           2.8879     23800      1.0         
20200705  221398        2.0           2.8881     23800      1.0         
20200706  192845 